name: swiftsuds-containers
services:
  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    container_name: order-api
    build:
      context: .
      dockerfile: src/SwiftSuds.Order.Api/Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql-server-2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password


